FROM sbasyal/docker-hub-demo:java-only

RUN touch /home/hello.txt \
    && touch /home/test-naming-convention.txt \
    && touch /home/testing-tag.txt

COPY Jenkins.png /home/test.png
COPY solutions-demos/docs/images/managing-expectations.gif /home/managing-expectations.gif